[package]
name = "tally-xml-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.183", features = ["derive"] }
typed-builder = "0.15.2"
xml_serde = "1.4.1"
